baseURL = "https://truslav.com/articles"
title = "Truslavistan State News Archive"
copyright = "The Ministry of Current Happenings"
theme = "newsprint"
canonifyurls = true
paginate = 5
assetDir = "/static"

[Params]
subtitle = "The Glorious Union of Truslavistan's Ministry of Current Happening's State News Archive."